### ISSUE TITLE
fun jsonRpcCall from class CallAgent throws an error on v 9.2.1

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#573]
Hi,

I was using CallAgent without the error at least up to v9.1.1, but when I bumped to v9.2.1 using jsonRpcCall function throws the following error:

```
TypeError: $this.this$0__1.callAgent_1.jsonRpcCall$default_gnxp4f_k$ is not a function
```

It happens with both of the two available versions of the class: CallAgent (from kilua-rpc) and KVCallAgent (from KVision)

Any insight will be greately appreciated.

Thanks

Teo

**Comment by rjaros** [comment]
Hi,

I think it could be also caused by https://youtrack.jetbrains.com/issue/KT-82005 
`KVCallAgent` class is a temporary workaround for the issue, but it might not work when used directly from the application code. Do you have an example project you can share?

**Comment by rjaros** [comment]
I confirm this is the same problem. When running with KVision snapshot built with 2.3.0-RC-214 the issue doesn't occur any more. I'll make a new version as soon as Kotlin 2.3.0-RC will be released. In the meantime as a workaround you can probably copy `CallAgent` class into your project.

**Comment by tfonrouge** [comment]
Hi.

I've already used a local copy of CallAgent as a temporary hack, but I wonder if any other classes were affected with the same issue and why ... So I'll gladly wait to the new release.


best regards,

Teo
